### ISSUE TITLE
AttributeError when running bot

### ISSUE THREAD

**Issue by deezed420** [Phxntxm/Bonfire#29]
When I run the bot (in a repl on replit) it throws the error:
```python
Traceback (most recent call last):
  File "bot.py", line 140, in <module>
    bot.loop.create_task(bot.cache.setup())
  File "<My computer>/venv/lib/python3.10/site-packages/discord/client.py", line 140, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook
```

**Comment by Phxntxm** [comment]
This bot was built on quite an old discord.py version... then was stopped. I don't do any support or work for this project anymore, sorry, I doubt there are many things that would even work with this anymore - with the current version of discord.py

**Comment by deezed420** [comment]
What discord.py version did it use? I still want to use your bot since this is a very cool creation

**Comment by Phxntxm** [comment]
Iirc, it used v1.7.3

Just note, I can't guarantee that this will still work. Keep in mind that the discord API itself has updates, and their deprecation of API versions is not... perfect, which causes some of the updates to discord.py to be REQUIRED. Since I haven't kept up with discord.py, I do not know if any updates were required by the API. But good luck
